### ISSUE TITLE
Issue with step 4b.3. warp_swc_using_transformix.py script is missing

### ISSUE THREAD

**Issue by sbmcmahan** [htem/run_elastix#1]
I was able to complete all steps in the manual until I got to step 4b.3. I cannot find the python script used in the instructions.

**Comment by jasper-tms** [comment]
Thanks for pointing this out, and I apologize for missing that file! I forgot to copy it over from the repository where this code originally lived. The file you want is here: https://github.com/htem/GridTape_VNC_paper/blob/main/template_registration_pipeline/warp_swc_using_elastix_transform.py 
but that version has some features that are specific to doing VNC template alignment that I should probably take out when I put it into this repo, since this repo is in theory supposed to be more general-purpose than just working for VNC template alignment. So, soon I will make sure that a proper version of that file gets added to this repository, but until then feel free to use the version in the other repo.

**Comment by jasper-tms** [comment]
Very sorry for the delay. If you hadn't gotten the version from the other repo to work, please feel free to test the code I just pushed. There are updated instructions on this repo's README. If you have time to try this out, please let me know if it does or doesn't work for you. Happy to fix any mistakes I made.
